name: Deploy GitHub Pages site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate users.json manifest
        run: |
          mkdir -p _data
          files=$(ls _data/*.json 2>/dev/null | grep -v users.json | xargs -n 1 basename | jq -R . | jq -s .)
          echo "$files" > _data/users.json
          cat _data/users.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
